name: Scheduled Auto Access

concurrency:
  group: ${{ github.workflow }}
  #cancel-in-progress: false # 前のが終わるまで次を起動させない（またはスキップする）
  cancel-in-progress: true

on:
  schedule:
    # 30分おきに実行する設定
    # - cron: '*/30 * * * *'
    #- cron: '15,45 * * * *'
    # 毎時 00 分に実行
    #- cron: '0 * * * *'
    # 毎時 04 分に実行
    #- cron: '4 * * * *'
    # 毎時 12 分に実行
    # -     #-     #- cron
  workflow_dispatch: # ← これを書くと「手動実行」ボタンが出ます

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo' # 日本時間に設定

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Pythonの準備
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 必要な道具をインストール
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: プログラム実行
        env:
          TZ: Asia/Tokyo
          PYTHONUNBUFFERED: "1"  # ← これを追加！ログがリアルタイムに出るようになります
        run: python click_study.py

      - name: ログファイルを保存
        if: always() # 成功・失敗に関わらず保存
        uses: actions/upload-artifact@v4
        with:
          name: all-logs
          path: log_*.txt # ← タイムスタンプ付きの全ファイルを対象にする


